export const PROJECTS = [{
        id: 0,
        projectName: 'Restaurant Application',
        projectImage: '/assets/images/restaurant.jpg',
        githubLink: 'https://github.com/katahrekartik/restaurant',
        liveLink: 'http://myassignments.byethost24.com/foodzone/',
        projectreport: '',
        tools: 'HTML,CSS,Javascript',
        projectDescription: 'This is project description This is project description This is project description ',
    },

    {
        id: 1,
        projectName: 'Form Builder',
        projectImage: '/assets/images/form.jpg',
        tools: 'HTML,CSS,Javascript',
        githubLink: 'https://github.com/katahrekartik/formbuilder.github.io',
        liveLink: 'https://katahrekartik.github.io/formbuilder.github.io/',
        projectreport: '',

        projectDescription: 'This is project description This is project description This is project description ',
    },
    {
        id: 2,
        projectName: 'Travable - A portal for travel agents',
        projectImage: '/assets/images/travel.jpg',
        tools: 'HTML,CSS,Javascript',
        projectreport: '/assets/docs/projectreport.pdf',
        githubLink: '',
        liveLink: '',
        projectDescription: 'This is project description This is project description This is project description ',
    },
    {
        id: 3,
        projectName: 'Event Management Application',
        projectImage: '/assets/images/event.png',
        tools: 'HTML,CSS,Javascript',
        projectreport: '/assets/docs/projectreport.pdf',
        githubLink: '',
        liveLink: '',
        projectDescription: 'This is project description This is project description This is project description ',
    },
    {
        id: 4,
        projectName: 'Educational Website',
        projectImage: '/assets/images/education.jpg',
        tools: 'HTML,CSS,Javascript',
        githubLink: 'https://github.com/katahrekartik/mobishaala.assignment',
        liveLink: 'https://katahrekartik.github.io/mobishaala.assignment/',
        projectreport: '',
        projectDescription: 'This is project description This is project description This is project description ',
    },
    {
        id: 5,
        projectName: 'Car rentals',
        projectImage: '/assets/images/car.jpg',
        tools: 'HTML,CSS,Javascript',
        githubLink: 'https://github.com/katahrekartik/assignment.whitepanda',
        liveLink: 'https://katahrekartik.github.io/carrentals/',
        projectreport: '',
        projectDescription: 'This is project description This is project description This is project description ',
    },
    {
        id: 6,
        projectName: 'Fusion - College  project',
        projectImage: '/assets/images/fusion.jpg',
        tools: 'HTML,CSS,Javascript',
        githubLink: 'https://github.com/katahrekartik/Fusion',
        liveLink: '',
        projectreport: '',
        projectDescription: 'This is project description This is project description This is project description ',
    },
    {
        id: 7,
        projectName: 'Smart Bin application',
        projectImage: '/assets/images/smartbin.jpg',
        tools: 'HTML,CSS,Javascript',
        githubLink: 'https://github.com/katahrekartik/Smart-bin-android-application',
        liveLink: '',
        projectreport: '',
        projectDescription: 'This is project description This is project description This is project description ',
    },
    {
        id: 8,
        projectName: 'Landing page',
        projectImage: '/assets/images/landing.png',
        tools: 'HTML,CSS,Javascript',
        githubLink: 'https://github.com/katahrekartik/quilhash.github.io',
        liveLink: 'https://katahrekartik.github.io/quilhash.github.io/',
        projectreport: '',
        projectDescription: 'This is project description This is project description This is project description ',
    },
];